// REPORT.md: the page a human reads on GitHub after each run.
const cell = (v) => String(v ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');
const rank = (r) => (r === undefined ? '–' : typeof r === 'number' ? '#' + r : r === 'mentioned' ? 'mentioned' : String(r));
const base = (v) => (v === undefined ? '' : v === 'No' ? '–' : typeof v === 'number' ? '#' + v : String(v));

export function renderReport(cfg, snaps, events, runDate) {
  const client = cfg.client.name;
  const lists = cfg.pages.filter((p) => p.type === 'list');
  const factPages = cfg.pages.filter((p) => (p.facts || []).length);
  const ok = Object.values(snaps).filter((s) => s && s.status === "ok").length;
  const listed = lists.filter((p) => typeof snaps[p.id]?.ranks?.[client] === 'number');
  const out = [];
  out.push(`# Source watch: ${client}`, '');
  out.push(`Last run: **${runDate}** · ${ok} of ${cfg.pages.length} pages read · ${client} ranked on **${listed.length} of ${lists.length}** cited lists · audit baseline: ${cfg.baseline_date}`, '');
  out.push('Generated by `.github/workflows/watch.yml`. Edit `watchlist.json` to change what is watched. History: `data/history.csv`.', '');

  out.push('## Changes this run', '');
  const shown = events.filter((e) => e.severity !== 'low' || e.kind !== 'fetch');
  if (!shown.length) out.push('No changes since the last run.', '');
  else {
    const order = { high: 0, medium: 1, low: 2 };
    for (const e of [...shown].sort((a, b) => order[a.severity] - order[b.severity])) out.push(`- **${e.severity}** · ${cell(e.title)}${e.action ? ` → ${cell(e.action)}` : ''}`);
    out.push('');
  }

  out.push('## Facts quoted in the outreach', '');
  out.push('| Fact | Expected | Now | Status | Quoted in |', '|---|---|---|---|---|');
  for (const p of factPages) {
    const s = snaps[p.id];
    for (const f of p.facts) {
      const got = (s?.facts || []).find((x) => x.id === f.id);
      const status = !s || s.status !== 'ok' ? `not read (${s ? s.status : 'n/a'})` : got.ok ? 'OK' : '**CHANGED**';
      out.push(`| [${cell(f.label)}](${p.url}) | ${cell(f.expect ?? f.expected)} | ${cell(got ? got.value ?? 'not found' : '')} | ${status} | ${cell(f.used_in)} |`);
    }
  }
  out.push('');

  out.push(`## Lists the AI assistants cite`, '');
  out.push(`Ranks are read from the page's own numbering, or else from the order of product headings. "mentioned" = named in the text but not as a list entry.`, '');
  const comp = cfg.competitors;
  out.push(`| Page | ${client} now | ${client} on ${cfg.baseline_date} | ${comp.join(' | ')} | Items | Page updated | Read |`);
  out.push(`|---|---|---|${comp.map(() => '---').join('|')}|---|---|---|`);
  const sorted = [...lists].sort((a, b) => Number(!!b.priority) - Number(!!a.priority) || a.publisher.localeCompare(b.publisher));
  for (const p of sorted) {
    const s = snaps[p.id] || {};
    const okp = s.status === 'ok';
    const tag = (p.priority ? ' ★' : '') + (p.vendor ? ' (vendor)' : '') + (p.subject ? ` (${p.subject} alternatives)` : '');
    out.push(`| [${cell(p.publisher)}](${p.url})${tag} | ${okp ? rank(s.ranks[client]) : '?'} | ${base(p.baseline?.[client])} | ${comp.map((c) => (okp ? rank(s.ranks[c]) : '?')).join(' | ')} | ${okp ? s.length : ''} | ${s.dates?.modified || ''} | ${s.status || 'n/a'} |`);
  }
  out.push('', '★ = a page named in the recommendations. Blocked pages (bot protection) are kept in the list and re-tried each run.', '');
  return out.join('\n');
}
